use serde::{Deserialize, Serialize};

/// Supported SNS platforms
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Platform {
    X,
    Tiktok,
    Instagram,
    Youtube,
}

impl Platform {
    pub fn as_str(&self) -> &'static str {
        match self {
            Platform::X => "x",
            Platform::Tiktok => "tiktok",
            Platform::Instagram => "instagram",
            Platform::Youtube => "youtube",
        }
    }

    pub fn max_chars(&self) -> usize {
        match self {
            Platform::X => 280,
            Platform::Tiktok => 2200,
            Platform::Instagram => 2200,
            Platform::Youtube => 100, // title limit
        }
    }
}

/// Content format types for different platform outputs
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum ContentFormat {
    Tweet,
    Thread,
    TiktokVideo,
    Reel,
    FeedImage,
    Carousel,
    Story,
    Short,
    YoutubeVideo,
}

impl std::fmt::Display for Platform {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// A single generated post ready for scheduling
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedPost {
    pub platform: String,
    pub text: String,
    pub hashtags: Vec<String>,
    pub language: String,
    pub creative_angle: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_format: Option<String>,
    pub scheduled_at: String,
    pub day: u32,
    pub slot: u32,
}

/// Campaign strategy generated by Claude
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CampaignStrategy {
    pub theme: String,
    pub target_audience: String,
    pub key_messages: Vec<String>,
    pub content_calendar: Vec<DayPlan>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DayPlan {
    pub day: u32,
    pub focus: String,
    pub angles: Vec<String>,
}

/// Default optimal posting times in JST (3 slots matching Inngest cron: 6:30, 12:00, 18:30)
pub const OPTIMAL_HOURS_JST: [u32; 3] = [6, 12, 18];

/// Get platform-specific optimal posting hours in JST
pub fn optimal_hours_for_platform(platform: &str) -> &'static [u32] {
    match platform {
        "x" => &[6, 12, 18],
        "tiktok" => &[7, 12, 19, 21],
        "instagram" => &[8, 12, 17, 20],
        "youtube" => &[10, 14, 18],
        _ => &[6, 12, 18],
    }
}

/// Convert JST hour to UTC hour
pub fn jst_to_utc(jst_hour: u32) -> u32 {
    (jst_hour + 24 - 9) % 24
}
